[[session]]
name = "Downloads 📥"
path = "~/Downloads/"
startup_command = "ls"

[[session]]
name = "wezterm 🔧"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "nvim 🔧"
path = "~/.config/nvim"
startup_command = "nvim "

[[session]]
name = "karabinar 🔧"
path = "~/.config/karabiner"
startup_command = "nvim"

[[session]]
name = "scripts 🔧"
path = "~/local/bin"
startup_command = "nvim"

[[session]]
name = "sesh 🔧"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Dev 💻"
path = "~/dev"
startup_command = "l"

[[session]]
name = "Home 🏡"
path = "~/"
startup_command = "clear"



[[session]]
name = "Notes 📝"
path = "/Users/yosefsaaid/Library/Mobile Documents/iCloud~md~obsidian/Documents/Second Brain"
startup_command = "nvim"
