[colors.primary]
background = "#25283a"
foreground = "#c0caf5"
dim_foreground = "#a9b1d6"
bright_foreground = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#f7768e"

[colors.vi_mode_cursor]
text = "#1a1b26"
cursor = "#bb9af7"

[colors.search.matches]
foreground = "#1a1b26"
background = "#7aa2f7"

[colors.search.focused_match]
foreground = "#1a1b26"
background = "#9ece6a"

[colors.footer_bar]
foreground = "#1a1b26"
background = "#7aa2f7"

[colors.hints.start]
foreground = "#1a1b26"
background = "#f7768e"

[colors.hints.end]
foreground = "#1a1b26"
background = "#7aa2f7"

[colors.selection]
text = "#1a1b26"
background = "#f7768e"

[colors.normal]
black = "#292e42"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.dim]
black = "#292e42"
red = "#db4b4b"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[[colors.indexed_colors]]
index = 16
color = "#e0af68"

[[colors.indexed_colors]]
index = 17
color = "#f7768e"

